/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author 55129
 */
public class Agenda extends javax.swing.JFrame {

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jHora = new javax.swing.JLabel();
        jvalor = new javax.swing.JLabel();
        jCliente = new javax.swing.JLabel();
        jServico = new javax.swing.JLabel();
        jComboCliente = new javax.swing.JComboBox<>();
        jData = new javax.swing.JLabel();
        jDescricao = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jObservacao = new javax.swing.JLabel();
        jComboServico = new javax.swing.JComboBox<>();
        textValor = new javax.swing.JTextField();
        textHora = new javax.swing.JTextField();
        textData = new javax.swing.JTextField();
        textId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jId.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jId.setText("ID");
        getContentPane().add(jId, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 0, 56)); // NOI18N
        jLabel2.setText("Agenda");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, -90, 320, 300));

        jHora.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jHora.setText("Hora");
        getContentPane().add(jHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        jvalor.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jvalor.setText("Servico");
        getContentPane().add(jvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        jCliente.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jCliente.setText("Data");
        getContentPane().add(jCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        jServico.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jServico.setText("Cliente");
        getContentPane().add(jServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, 30));

        jComboCliente.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(jComboCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 130, -1));

        jData.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jData.setText("Valor R$");
        getContentPane().add(jData, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        jDescricao.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(jDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 240, 170));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setText("Agendar");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 240, -1));

        jObservacao.setFont(new java.awt.Font("Showcard Gothic", 0, 14)); // NOI18N
        jObservacao.setText("Observacao");
        getContentPane().add(jObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        jComboServico.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(jComboServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 130, -1));

        textValor.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(textValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 130, -1));

        textHora.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(textHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 130, -1));

        textData.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(textData, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 130, -1));

        textId.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(textId, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 130, -1));

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 0, 11)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/agenda.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jCliente;
    private javax.swing.JComboBox<String> jComboCliente;
    private javax.swing.JComboBox<String> jComboServico;
    private javax.swing.JLabel jData;
    private javax.swing.JTextField jDescricao;
    private javax.swing.JLabel jHora;
    private javax.swing.JLabel jId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jObservacao;
    private javax.swing.JLabel jServico;
    private javax.swing.JLabel jvalor;
    private javax.swing.JTextField textData;
    private javax.swing.JTextField textHora;
    private javax.swing.JTextField textId;
    private javax.swing.JTextField textValor;
    // End of variables declaration//GEN-END:variables
}
