/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author 55129
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textsenha = new javax.swing.JTextField();
        textusuario = new javax.swing.JTextField();
        senha = new javax.swing.JLabel();
        usuario = new javax.swing.JLabel();
        login = new javax.swing.JLabel();
        jfundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textsenha.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(textsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 250, 30));

        textusuario.setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().add(textusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 250, 30));

        senha.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        senha.setText("Senha");
        getContentPane().add(senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 250, 40));

        usuario.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        usuario.setText("Usuario");
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 250, 40));

        login.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        login.setText("         Login");
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 250, 40));

        jfundo.setForeground(new java.awt.Color(153, 153, 255));
        jfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Imagens/Teladelogin.jpeg"))); // NOI18N
        getContentPane().add(jfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jfundo;
    private javax.swing.JLabel login;
    private javax.swing.JLabel senha;
    private javax.swing.JTextField textsenha;
    private javax.swing.JTextField textusuario;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
